"use client"

import './globals.css'

import "@walmart-web/livingdesign-components/index.esm.css";
// import "@walmart-web/livingdesign/bogle/dist/Bogle.css";


import { LivingDesignProvider } from "@walmart-web/livingdesign-components";
import Menu from './ui/Menu';
import SideNav from './ui/SideNav';
import Breadcrumbs from './ui/Breadcrumbs';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <LivingDesignProvider>

          <div className="w-full h-[50px] bg-[#0071dc] flex items-center p-2">
            <div className='text-white font-bold text-2xl'>Waldocs</div>
          </div>

          <main className="grid grid-cols-12 min-h-screen h-screen">

            <div className="col-span-2">
              <Menu></Menu>
              <SideNav></SideNav>
            </div>            

            <div className="container mx-auto col-span-10 p-5">
              <Breadcrumbs/>
              {children}
            </div>

          </main>

        </LivingDesignProvider>
      </body>
    </html>
  )
}
